#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - categories/about.md
  - categories/project.md
  - categories/study.md

footer: 'Visit my <a href="https://github.com/juhyeonlee134">Github</a>'

style: dark

plugins:
  - jekyll-seo-tag
